### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lceShell** [sryu1/YouTube_View_Bot#2]
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
[286532:285876:0721/104710.853:ERROR:device_event_log_impl.cc(214)] [10:47:10.853] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
[291800:291772:0721/104905.163:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

How do i fix (in both bot gui and bot

**Comment by sryu1** [comment]
Actually, could you first try downgrading your selenium to 4.1.0 before trying anything else?
If you get the warning below with 4.1.0, you can ignore it unless the video doesn't start playing automatically.
DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  drivers[i].find_element_by_css_selector('[title^="Play (k)"]').click()

**Comment by sryu1** [comment]
Actually, could you first try by downgrading selenium to 4.1.0?
If you get the error below, ignore it unless, the video doesn't autoplay. 
DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  drivers[i].find_element_by_css_selector('[title^="Play (k)"]').click()

**Comment by lceShell** [comment]
chrome only has the version 103.0.5060.134 for me and no updates are avalable, i dont know why thats why i have to use the other version of selencium and i dont have bloototh on my pc

**Comment by lceShell** [comment]
and in administrator the bot wont start

**Comment by sryu1** [comment]
Do you have chromedriver 104.x or 103.x in your python directory?

**Comment by sryu1** [comment]
Selenium 4.3.0 doesn't work with this, that's why I'd like you to try selenium 4.1.0 and see if it works.

**Comment by lceShell** [comment]
> Do you have chromedriver 104.x or 103.x in your python directory?

103

**Comment by lceShell** [comment]
zevkev#4026 can you add me on dc its easyer for me to speak there

**Comment by sryu1** [comment]
This issue has been resolved through release 2.0.4
